sudo: required
dist: trusty
language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y dpkg
  - sudo apt-get install -qq multistrap patch
  - (cd / && sudo patch -p1) < ./.travis/multistrap-forceyes.patch

script:
  - ./build.sh

after_success:
  - ./.travis/deploy.sh
